badhai_ho/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shaadi.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shaadi/urls.py
from django.urls import path
from . import views

app_name = 'shaadi'

urlpatterns = [
	path("", views.login, name="login"),
	path('create_customer/', views.create_customer, name="create_customer"),
	path('<int:customer_id>/home/', views.home, name="home"),
	path('<int:customer_id>/home/<int:category_id>/', views.dealer, name="dealer"),
	path('<int:customer_id>/home/<int:category_id>/<int:dealer_id>/', views.dealer_info, name="dealer_info"),
	path('<int:customer_id>/home/<int:category_id>/<int:dealer_id>/details', views.detail, name="detail"),
]

shaadi/models.py
from django.db import models
from ckeditor.fields import RichTextField
from embed_video.fields import EmbedVideoField
from ckeditor import static

class Category(models.Model):
	category = models.CharField(max_length=50, null=True, blank=True)
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return f"{self.category}"

class Dealer(models.Model):
	company_name = models.CharField(max_length=100, null=True, blank=True)
	head_name = models.CharField(max_length=50, null=True, blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	exp = models.IntegerField(blank=True, null=True)
	stars = models.IntegerField(default=0, blank=True, null=True)
	suggestions = models.TextField(blank=True, null=True)
	logo = models.ImageField(blank=True, null=True)

	def __str__(self):
		return f"{self.company_name}"

class Help(models.Model):
	dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE)
	discount = RichTextField(max_length=100000, blank=True, null=True)
	offers = RichTextField(max_length=100000, blank=True, null=True)

	def __str__(self):
		return f"{self.dealer.company_name}"

class Customer(models.Model):
	name = models.CharField(max_length=50, blank=True, null=True)
	email = models.CharField(max_length=100, blank=True, null=True, unique=True)
	password = models.CharField(max_length=15, blank=True, null=True)
	phone = models.CharField(max_length=12, blank=True, null=True, unique=True)
	address = RichTextField(max_length=1000, blank=True, null=True)
	state = models.CharField(max_length=100, blank=True, null=True)
	city = models.CharField(max_length=100, blank=True, null=True)
	membership = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.name}"

class Book(models.Model):
	start_date = models.DateField()
	end_date = models.DateField()
	marriage_date = models.DateField()
	dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE)
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.dealer}"

shaadi/forms.py
from django import forms
from .models import Category, Dealer, Help, Customer, Book

class create_customerForm(forms.Form):
	STATES = (
		('None', 'None'),
		('Delhi', 'Delhi'),
		('Maharashtra', 'Maharashtra'),
		('West Bengal', 'West Bengal'),
		('Rajasthan', 'Rajasthan'),
	)
	CITY = (
		('None', 'None'),
		('New Delhi', 'New Delhi'),
		('Mumbai', 'Mumbai'),
		('Kolkata', 'Kolkata'),
		('Jaipur', 'Jaipur'),
	)
	name = forms.CharField(max_length=100, widget=forms.TextInput(
			attrs={
				'class':'input100',
				'type':'text',
				'name':'name',
				'placeholder':'Name...',
				'id': 'validationTooltip01',
			}
		))
	phone = forms.CharField(widget=forms.TextInput(
			attrs={
				'class':'input100',
				'type':'text',
				'name':'phone',
				'placeholder':'phone',
				'id': 'validationTooltip02',
			}
		))
	email = forms.CharField(max_length=100, widget=forms.EmailInput(
			attrs={
				'class':'input100',
				'type':'text',
				'name':'email',
				'placeholder':'Email addess...',
				'id': 'validationTooltip03',
			}
		))	
	password = forms.CharField(max_length=100, widget=forms.PasswordInput(
			attrs={
				'class':'input100',
				'type':'text',
				'name':'pass',
				'placeholder':'*************',
				'id': 'validationTooltip04',
			}
		))	 	
	address = forms.CharField(widget=forms.TextInput(
			attrs={
				'class': 'input100',
				'type':'text',
				'name':'pass',
				'placeholder': 'address',
				'id': 'validationTooltip05',
			}
		))	
	state = forms.ChoiceField(widget=forms.Select(
				attrs={
					'class': 'input100',
					'type':'text',
					'name':'pass',
					'placeholder': 'state',
					'id': 'validationTooltip06',
				}
			), choices=STATES)

	city = forms.ChoiceField(widget=forms.Select(
				attrs={
					'class': 'input100',
					'type':'text',
					'name':'pass',
					'placeholder': 'city',
					'id': 'validationTooltip07',
				}
			), choices=CITY)

class loginForm(forms.Form):
	email = forms.CharField(max_length=100, widget=forms.EmailInput(
			attrs={
				'class': 'input100',
				'placeholder': 'email',
				'id': 'validationTooltip03',
			}
		))
	password = forms.CharField(max_length=100, widget=forms.PasswordInput(
			attrs={
				'class': 'input100',
				'placeholder': 'password',
				'id': 'validationTooltip04',
			}
		))	 

class detailForm(forms.Form):
	start_date = forms.DateField(widget=forms.DateInput(
			attrs={
				'class': 'form-control',
				'type':'date',
				'placeholder': 'start date',
				'id': 'validationTooltip08',
			}
		))	 

	end_date = forms.DateField(widget=forms.DateInput(
			attrs={
				'class': 'form-control',
				'type':'date',
				'placeholder': 'end date',
				'id': 'validationTooltip09',
			}
		))	 

	marriage_date = forms.DateField(widget=forms.DateInput(
			attrs={
				'class': 'form-control',
				'type':'date',
				'placeholder': 'marriage date',
				'id': 'validationTooltip010',
			}
		))	 

shaadi/views.py
from django.shortcuts import render
from .models import Category, Dealer, Help, Customer, Book
from .forms import loginForm, create_customerForm, detailForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import redirect

def home(request, customer_id):
	category = Category.objects.all()
	customer = Customer.objects.get(pk=customer_id)
	context = {
		'category':category,
		'customer':customer,
	}
	return render(request, "shaadi/home.html", context)

def dealer(request, customer_id, category_id):
	category = Category.objects.get(pk=category_id)
	dealer = Dealer.objects.filter(category=category_id)
	customer = Customer.objects.get(pk=customer_id)
	context = {
		'dealer':dealer,
		'customer':customer,
		'category':category,
	}
	return render(request, "shaadi/dealer.html", context)

def dealer_info(request, customer_id, category_id, dealer_id):
	category = Category.objects.get(pk=category_id)
	dealer = Dealer.objects.get(pk=dealer_id)
	customer = Customer.objects.get(pk=customer_id)
	context = {
		'dealer':dealer,
		'customer':customer,
		'category':category,
	}
	return render(request, "shaadi/dealer_info.html", context)

def login(request):
	customer = Customer.objects.all()
	if request.method == 'POST':
		form = loginForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			for customer in customer:
				if email == customer.email and password == customer.password:
					context = {
						'detail' : Book.objects.get(customer=customer),
						'customer' : customer,
					}
					return render(request, "shaadi/registered_detail.html", context)
			else:
				return HttpResponseRedirect("")
	else:
		form = loginForm()
	context = {
		'form' : form,
	}
	return render(request, 'shaadi/login.html', context)

def create_customer(request):
	if request.method == 'POST':
		form = create_customerForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			phone = form.cleaned_data['phone']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			address = form.cleaned_data['address']
			state = form.cleaned_data['state']
			city = form.cleaned_data['city']
			customer = Customer.objects.create(name=name, phone=phone, email=email, password=password, address=address, state=state, city=city)
			customer.save()
			customer_id = customer.id
			response = reverse('shaadi:home', kwargs={'customer_id':customer_id})
			return redirect(response)

	else:
		form = create_customerForm()
	context = {
		'form' : form,
	}
	return render(request, 'shaadi/create_customer.html', context)

def detail(request, customer_id, category_id, dealer_id):
	customer = Customer.objects.get(pk=customer_id)
	category = Category.objects.get(pk=category_id)
	dealer = Dealer.objects.get(pk=dealer_id)
	if request.method == 'POST':
		form = detailForm(request.POST)
		if form.is_valid():
			start_date = form.cleaned_data['start_date']
			end_date = form.cleaned_data['end_date']
			marriage_date = form.cleaned_data['marriage_date']
			book = Book.objects.create(start_date=start_date, end_date=end_date, marriage_date=marriage_date, dealer=dealer, customer=customer)
			book.save()
			return HttpResponse("You have succesfully registered")
	else:
		form = detailForm()
	context = {
		'form':form,
		'customer':customer,
		'dealer':dealer,
		'category':category,
	}
	return render(request, 'shaadi/detail.html', context)

shaadi/templates/shaadi/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	{% block head %}
	{% endblock %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
	</script>
	<link rel="stylesheet" type="text/css" href="{% static 'styles1.css' %}">
</head>
<body>
	{% block body %}
	{% endblock %}
</body>
</html>

shaadi/templates/shaadi/create_customer.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>New Account</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="https://colorlib.com/etc/lf/Login_v13/images/icons/favicon.ico" />

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/iconic/css/material-design-iconic-font.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/animate/animate.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/css-hamburgers/hamburgers.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/animsition/css/animsition.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/select2/select2.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/daterangepicker.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/css/util.css">
<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/css/main.css">

</head>
  <body style="background-color: #999999;">
    <div class="limiter">
      <div class="container-login100">
        <div class="login100-more" style="background-image: url('static/heart.jpg');">    
        </div>
        <div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50" >
          <form class="login100-form validate-form" action="{% url 'shaadi:create_customer' %}" method="post">
            {% csrf_token %}
            <span class="login100-form-title p-b-59">
              Sign Up
            </span>
            <div class="wrap-input100 validate-input" data-validate="Name is required">
              <span class="label-input100">Your Name</span>
              {{ form.name }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
              <span class="label-input100">Email</span>
              {{ form.email }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Username is required">
              <span class="label-input100">Phone</span>
              {{ form.phone }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Password is required">
              <span class="label-input100">Password</span>
              {{ form.password }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Address is required">
              <span class="label-input100">Address</span>
              {{ form.address }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="State is required">
              <span class="label-input100">State</span>
              {{ form.state }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="City is required">
              <span class="label-input100">City</span>
              {{ form.city }}
              <span class="focus-input100"></span>
            </div>
            <div class="flex-m w-full p-b-33">
              <div class="contact100-form-checkbox">
                <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                <label class="label-checkbox100" for="ckb1">
                  <span class="txt1">
                  I agree to the
                    <a href="#" class="txt2 hov1">
                    Terms of User
                    </a>
                  </span>
                </label>
              </div>
            </div>
            <div class="container-login100-form-btn">
              <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn">
              </div>
              <button class="login100-form-btn" type="submit">
                Sign Up
              </button>
            </div>
              <a href="{% url 'shaadi:login' %}" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
                Sign in
                <i class="fa fa-long-arrow-right m-l-5"></i>
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/jquery/jquery-3.2.1.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/animsition/js/animsition.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/js/popper.js" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script src="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/js/bootstrap.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/select2/select2.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/moment.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script src="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/daterangepicker.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/countdowntime/countdowntime.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/js/main.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script type="633c81bf56e6a384aa776133-text/javascript">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
  </script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js" data-cf-settings="633c81bf56e6a384aa776133-|49" defer=""></script>
</body>
</html>

shaadi/templates/shaadi/dealer_info.html
{% extends 'shaadi/base.html' %}

{% block title %}
	{{ dealer.company_name }}
{% endblock %}

{% block body %}
	<div style="color: white">
		<label>Company Name : </label>{{ dealer.company_name }}<br>
		<label>Head Name : </label>{{ dealer.head_name }}<br>
		<label>Category : </label>{{ dealer.category }}<br>
		<label>Experience : </label>{{ dealer.exp }} Years<br>
		<label>Stars : </label>{{ dealer.stars }}<br>
	</div>
	<form action="{% url 'shaadi:detail' customer.id category.id dealer.id %}">
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
{% endblock %}

shaadi/templates/shaadi/detail.html
{% extends 'shaadi/base.html' %}

{% block title %}
	Register
{% endblock %}

{% block body %}
<form action="{% url 'shaadi:detail' customer.id category.id dealer.id %}" method="post" class="needs-validation" novalidate>
	{% csrf_token %}
	<div>
		<div class="col-md-3 mb-3">
		    <label for="validationTooltip08"><strong>Starting Date</strong></label>
		      	{{ form.start_date }}
		</div>	    
		<div class="col-md-3 mb-3">
		    <label for="validationTooltip09"><strong>Ending Date</strong></label>
		    {{ form.end_date }}
		</div>
		<div class="col-md-3 mb-3">
		    <label for="validationTooltip010"><strong>Marriage Date</strong></label>
		    {{ form.marriage_date }}
		</div>	
		<br>
		<button class="btn btn-primary" type="submit">Pay</button>
	</div>
</form>
{% endblock %}

shaadi/templates/shaadi/login.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'login.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" action="{% url 'shaadi:login' %}" method="post">
      <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1>LOGIN</h1><br>
      <label for="inputEmail" class="sr-only">{{ form.email }}</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">{{ form.password }}</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <a href="{% url 'shaadi:create_customer' %}">Create New Account</a>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
    </form>
  </body>
</html>

shaadi/templates/shaadi/rough.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>New Account</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="https://colorlib.com/etc/lf/Login_v13/images/icons/favicon.ico" />

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/fonts/iconic/css/material-design-iconic-font.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/animate/animate.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/css-hamburgers/hamburgers.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/animsition/css/animsition.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/select2/select2.min.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/daterangepicker.css">

<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/css/util.css">
<link rel="stylesheet" type="text/css" href="https://colorlib.com/etc/lf/Login_v13/css/main.css">

</head>
  <body style="background-color: #999999;">
    <div class="limiter">
      <div class="container-login100">
        <div class="login100-more" style="background-image: url('static/heart.jpg');">    
        </div>
        <div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50" >
          <form class="login100-form validate-form" action="{% url 'shaadi:create_customer' %}" method="post">
            {% csrf_token %}
            <span class="login100-form-title p-b-59">
              Sign Up
            </span>
            <div class="wrap-input100 validate-input" data-validate="Name is required">
              <span class="label-input100">Your Name</span>
              {{ form.name }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
              <span class="label-input100">Email</span>
              {{ form.email }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Username is required">
              <span class="label-input100">Phone</span>
              {{ form.phone }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Password is required">
              <span class="label-input100">Password</span>
              {{ form.password }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="Address is required">
              <span class="label-input100">Address</span>
              {{ form.address }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="State is required">
              <span class="label-input100">State</span>
              {{ form.state }}
              <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input" data-validate="City is required">
              <span class="label-input100">City</span>
              {{ form.city }}
              <span class="focus-input100"></span>
            </div>
            <div class="flex-m w-full p-b-33">
              <div class="contact100-form-checkbox">
                <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                <label class="label-checkbox100" for="ckb1">
                  <span class="txt1">
                  I agree to the
                    <a href="#" class="txt2 hov1">
                    Terms of User
                    </a>
                  </span>
                </label>
              </div>
            </div>
            <div class="container-login100-form-btn">
              <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn">
              </div>
              <button class="login100-form-btn" type="submit">
                Sign Up
              </button>
            </div>
              <a href="{% url 'shaadi:login' %}" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
                Sign in
                <i class="fa fa-long-arrow-right m-l-5"></i>
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/jquery/jquery-3.2.1.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/animsition/js/animsition.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/js/popper.js" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script src="https://colorlib.com/etc/lf/Login_v13/vendor/bootstrap/js/bootstrap.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/select2/select2.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/moment.min.js" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script src="https://colorlib.com/etc/lf/Login_v13/vendor/daterangepicker/daterangepicker.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/vendor/countdowntime/countdowntime.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script src="https://colorlib.com/etc/lf/Login_v13/js/main.js" type="633c81bf56e6a384aa776133-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="633c81bf56e6a384aa776133-text/javascript"></script>
<script type="633c81bf56e6a384aa776133-text/javascript">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
  </script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js" data-cf-settings="633c81bf56e6a384aa776133-|49" defer=""></script>
</body>
</html>